version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  cheapolata.cyrhades.fr:
    image: anssi/fcsc2024-pwn-cheapolata:latest
    ports:
      - ${PORT_SSH}:4000
